# See: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Enable version updates for Golang
  - package-ecosystem: "gomod"
    directory: "/"
    commit-message:
      include: "scope"
      prefix: "go-dep"
    labels:
      - "dependency"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "dependency"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
