services:
  main:
    environment:
      GH_TOKEN: "${GH_TOKEN}"
      MODE: "DEV"
      NVIM_LANGUAGES: "go"
    hostname: "sshp-main"
    image: "ghcr.io/mklbravo/devimage:go-1.23"
    secrets:
      - "ssh_private_key"
    volumes:
      - "../:/src"
      - "~/.config/github-copilot:/root/.config/github-copilot"
      - "${SSH_PRIVATE_KEY}.pub:/root/.ssh/id_rsa.pub:ro"
    working_dir: "/src"

secrets:
  ssh_private_key:
    file: "${SSH_PRIVATE_KEY}"
